title:              Breanna Zavadoff, PhD
email:              bzavadoff@rsmas.miami.edu
description:        Atmospheric Scientist
author:             Breanna Zavadoff
baseurl:            ""
url:                "https://breannazavadoff.github.io"

# Social Profiles
twitter_username:   breannazavadoff
github_username:    bzavadoff
facebook_username:  
instagram_username: bzavadoff 
linkedin_username: breannazavadoff

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
